name: Deployment

on:
  push:
    branches: [dev, main]

env:
  AWS_REGION: us-east-1
  ECR_REPO_NAME: templates-scheduled-job

permissions:
      id-token: write
      contents: read

jobs:
  build:
    name: "Build docker image"
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: temporary
        name: Print some variables
        run: |
          echo ${GITHUB_SHA}
          echo ${GITHUB_REF}

      - id: aws-configure
        name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GHA_ASSUMED_ROLE }}
#          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

#      - id: build
#        uses: docker/setup-buildx-action@v3
#        env:
#          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
#          ECR_REPOSITORY: ${{ env.ECR_REPO_NAME }}
#        with:
#          context: .
#          build-args: ${GITHUB_SHA}
#          tags:
#            - ${{ECR_REGISTRY}}/${ECR_REPOSITORY}-${GITHUB_SHA}

      - id: build-and-push
        name: push image to Amazon ECR
        shell: bash
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: ${{ env.ECR_REPO_NAME }}
          IMAGE_TAG: "today"-$GITHUB_SHA
        run: |
          docker build -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" --build-arg GITHUB_SHA_ARG=$GITHUB_SHA .
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "image_tag=$IMAGE_TAG" 
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"