name: Deployment

on:
  push:
    branches: [main]


jobs:

  build:
    name: "Build docker image"
    runs-on: self-hosted
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: temporary
        name: Print some variables
        run: |
          echo ${GITHUB_SHA}
          echo ${GITHUB_REF}

      - id: build
        uses: docker/setup-buildx-action@v3
        run: |
          docker build --build-arg=${GITHUB_SHA} .

