name: Deployment

on:
  push:
    branches: [dev, main]


jobs:

  build:
    name: "Build docker image"
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: temporary
        name: Print some variables
        run: |
          echo ${GITHUB_SHA}
          echo ${GITHUB_REF}

      - id: build
        uses: docker/setup-buildx-action@v3
        with:
          context: .
          build-args: ${GITHUB_SHA}
